services:
  - type: web
    name: cars-g-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: WS_PORT
        value: 3001
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://cars-g.vercel.app
    healthCheckPath: /health
    autoDeploy: true 
  - type: cron
    name: cars-g-keepalive
    schedule: "*/5 * * * *"
    command: curl -fsS "https://cars-g-api.onrender.com/health" || true