// Vercel serverless function for email verification confirmation
// GET endpoint for email verification token validation

import { createClient } from '@supabase/supabase-js';

// Initialize Supabase client
const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  throw new Error('Missing Supabase configuration');
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

// Generate success HTML page
function generateSuccessHTML(firstName, email) {
  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Email Verified - CARS-G</title>
        <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; text-align: center; }
            .header { background: linear-gradient(135deg, #28a745 0%, #20c997 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
            .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
            .success-icon { font-size: 48px; color: #28a745; margin: 20px 0; }
            .button { display: inline-block; background: #667eea; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; font-weight: bold; margin: 20px 0; }
            .button:hover { background: #5a6fd8; }
            .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🚗 CARS-G</h1>
            <p>Community Safety Platform</p>
        </div>
        
        <div class="content">
            <div class="success-icon">✅</div>
            <h2>Email Verified Successfully!</h2>
            <p>Hi ${firstName}, your email <strong>${email}</strong> has been verified.</p>
            
            <p><strong>Next Steps:</strong></p>
            <ol style="text-align: left; max-width: 400px; margin: 0 auto;">
                <li>Upload your ID documents for verification</li>
                <li>Wait for admin approval</li>
                <li>Start contributing to community safety!</li>
            </ol>
            
            <div style="margin-top: 30px;">
                <a href="/upload-id" class="button">Continue to ID Upload</a>
            </div>
        </div>
        
        <div class="footer">
            <p>This page was generated by CARS-G Community Safety Platform</p>
        </div>
    </body>
    </html>
  `;
}

// Generate error HTML page
function generateErrorHTML(errorMessage) {
  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Verification Error - CARS-G</title>
        <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; text-align: center; }
            .header { background: linear-gradient(135deg, #dc3545 0%, #fd7e14 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
            .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
            .error-icon { font-size: 48px; color: #dc3545; margin: 20px 0; }
            .button { display: inline-block; background: #667eea; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; font-weight: bold; margin: 20px 0; }
            .button:hover { background: #5a6fd8; }
            .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🚗 CARS-G</h1>
            <p>Community Safety Platform</p>
        </div>
        
        <div class="content">
            <div class="error-icon">❌</div>
            <h2>Verification Failed</h2>
            <p>${errorMessage}</p>
            
            <div style="margin-top: 30px;">
                <a href="/register" class="button">Try Again</a>
            </div>
        </div>
        
        <div class="footer">
            <p>This page was generated by CARS-G Community Safety Platform</p>
        </div>
    </body>
    </html>
  `;
}

export default async function handler(req, res) {
  // Enable CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'GET') {
    return res.status(405).json({ success: false, error: 'Method not allowed' });
  }

  try {
    const { token } = req.query;

    if (!token) {
      return res.status(400).send(generateErrorHTML('Verification token is missing. Please check your email and try again.'));
    }

    // Find user with matching verification token
    const { data: user, error: userError } = await supabase
      .from('profiles')
      .select('id, email, first_name, email_verification_token, email_verification_token_expiry, verification_status')
      .eq('email_verification_token', token)
      .eq('verification_status', 'pending_email_verification')
      .single();

    if (userError || !user) {
      return res.status(400).send(generateErrorHTML('Invalid or expired verification token. Please request a new verification email.'));
    }

    // Check if token is still valid (not expired)
    const now = new Date();
    const tokenExpiry = new Date(user.email_verification_token_expiry);
    
    if (tokenExpiry < now) {
      return res.status(400).send(generateErrorHTML('Verification token has expired. Please request a new verification email.'));
    }

    // Update user status to pending admin approval
    const { error: updateError } = await supabase
      .from('profiles')
      .update({
        email_verified: true,
        verification_status: 'pending_admin_approval', // Updated status as requested
        email_verification_token: null,
        email_verification_token_expiry: null,
        updated_at: new Date().toISOString()
      })
      .eq('id', user.id);

    if (updateError) {
      console.error('Error updating user verification status:', updateError);
      return res.status(500).send(generateErrorHTML('Failed to confirm email verification. Please try again.'));
    }

    // Also update the auth user to mark email as confirmed
    const { error: authUpdateError } = await supabase.auth.admin.updateUserById(user.id, {
      email_confirm: true
    });

    if (authUpdateError) {
      console.error('Error updating auth user email confirmation:', authUpdateError);
      // Don't fail the request, just log the error
    }

    // Return success page
    return res.status(200).send(generateSuccessHTML(user.first_name, user.email));

  } catch (error) {
    console.error('Email verification error:', error);
    return res.status(500).send(generateErrorHTML('Internal server error. Please try again later.'));
  }
}